config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root                'static_pages#home'
  get    'help'    => 'users#help'
  get    'about'   => 'static_pages#about'
  get    'contact.rb' => 'static_pages#contact.rb'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new' #login page
  post   'login'   => 'sessions#create' #actual log in process
  delete 'logout'  => 'sessions#destroy'
  get    'contacts' => 'contacts#new'

  resources :users do
    member do
      get :following, :followers #member makes sure that the url is users/id/following so the id is included
    end
  end

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contacts,           only: [:new, :create]


  mount Ckeditor::Engine => '/ckeditor'

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :posts
  belongs_to :user

  scope :film, -> { where(name: 'film') }
  scope :music, -> {where(name: 'music')}
  scope :life, -> {where(name: 'life')}

  validate :name_options


  private

  def name_options
    if ["film","music","life"].include?(self.name)
    else
      errors.add(:name, "film, music, or life only")
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy, :edit]
  has_scope :film
  has_scope :music
  has_scope :life

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.friendly.find(params[:id])
    @posts = @topic.posts.paginate(:page => params[:page], :per_page => 10).order("created_at desc")

    set_meta_tags :og => {
                      :title    => @topic.name,
                      :description => "Film reviews, interviews, and essays for moviegoers of all shapes and sizes."
                  }

    set_meta_tags :description => "Film reviews, interviews, and essays for moviegoers of all shapes and sizes."
  end

  # GET /topics/new
  def new
    if logged_in?
      @topic = Topic.new
      @topic.posts.build
    else
      redirect_to root_path
      flash[:info] = "You're not authorized to make a topic"
    end
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :name,
                                    post_attributes: [:id, :name, :title, :user_id,
                                                      :topic_id, :content, :created_at, :updated_at, :picture])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@search, :url => { :action => 'index' }, :html => {:method => :get} ) do |f| %>
    <%= f.text_field(:name) %>
    <%= f.submit "Filter List" %>
<% end %>

<%= @topics.each do |topic| %>
    <% render topic.posts %>
<% end %>

<br>
<% if logged_in? %>
    <%= link_to 'New Topic', new_topic_path %>
<% end %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<% provide(:title, "#{@topic.name.capitalize} Posts") %>
<head>
  <%= display_meta_tags %>
</head>
<div class="container">
<h1>
  <%= @topic.name.capitalize %> Posts
</h1>
<% if @topic.posts.any? %>
    <h3>Posts (<%= @topic.posts.count %>)</h3>
    <hr>
    <p>
      <%= render 'shared/feed' %>
    </p>
<% end %>

<h4><%= link_to 'Back', url_for(:back) %></h4>
</div>