config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root                'static_pages#home'
  get    'help'    => 'users#help'
  get    'about'   => 'static_pages#about'
  get    'contact.rb' => 'static_pages#contact.rb'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new' #login page
  post   'login'   => 'sessions#create' #actual log in process
  delete 'logout'  => 'sessions#destroy'
  get    'contacts' => 'contacts#new'

  resources :users do
    member do
      get :following, :followers #member makes sure that the url is users/id/following so the id is included
    end
  end

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contacts,           only: [:new, :create]


  mount Ckeditor::Engine => '/ckeditor'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
        <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% @posts.each do |post| %>
<div class="row">
  <div class="col-xs-6">
        <h3><%= link_to post.title.html_safe, post %></h3>
    <p>by <%= link_to post.user.name, post.user %> on
      <%= post.created_at.in_time_zone.strftime('%m/%d/%y')%> under
      <%= link_to post.topic.name, post.topic %></p>
      <%=  truncate(post.content, :length => 50, :escape => false).html_safe %>
    <h5><%= link_to pluralize(post.comments.count, 'Comment'), post_path(post, :anchor => "comments") unless post.comments.count == 0 %></h5>
    <h5><%= pluralize(post.impressionist_count, 'View') %></h5>
  </div>
  <div class="col-xs-6">
        <h2><%= image_tag post.picture.url, :width => "100%" %></h2>
  </div>
</div>
    <hr>
<% end %>
<%= will_paginate @posts %>

app/views/shared/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %> <%# Note email_feild, password_field make it have specific keyboard characeteristics %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control'%>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %> <%# Bc for the stats on the profile page it's @user, but for the home page it's current_user (bc @user will be nil)%>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my awesomeness", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>