config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root                'static_pages#home'
  get    'help'    => 'users#help'
  get    'about'   => 'static_pages#about'
  get    'contact.rb' => 'static_pages#contact.rb'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new' #login page
  post   'login'   => 'sessions#create' #actual log in process
  delete 'logout'  => 'sessions#destroy'
  get    'contacts' => 'contacts#new'

  resources :users do
    member do
      get :following, :followers #member makes sure that the url is users/id/following so the id is included
    end
  end

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contacts,           only: [:new, :create]


  mount Ckeditor::Engine => '/ckeditor'

end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  has_many :comments
  belongs_to :user
  belongs_to :topic

  is_impressionable

  accepts_nested_attributes_for :topic, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  mount_uploader :picture, PictureUploader

  validates :user_id, presence: true
  validates :title, presence: true
  validates :caption, presence: true
  validates :content, length: {minimum: 5}
  validate :picture_size

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def self.search(search)
    if search.blank? || search == {"topic_id"=>""}
      default_scoped.order('created_at DESC')
    else
      where(:posts => search).order('created_at DESC')
    end
  end

  def slug_candidates
    [
        :title,
        [:created_at, :title]
    ]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::TextHelper

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy, :edit]
  after_filter "save_my_previous_url", only: [:new]



  # GET /posts
  # GET /posts.json

  def index
    @posts = Post.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    impressionist(@post)
    @recent_posts = Post.includes([:comments,:topic]).order("created_at desc").limit(10)

    set_meta_tags :og => {
                      :title    => @post.title,
                      :image    => @post.picture
                  }

    set_meta_tags :twitter => {
                      :card    => "summary",
                      :title    => @post.title,
                      :image    => @post.picture,
                      :description => @post.caption
                  }

    set_meta_tags :image => @post.picture,
        :description => @post.caption
  end

  def save_my_previous_url
    # session[:previous_url] is a Rails built-in variable to save last url.
    session[:my_previous_url] = URI(request.referer || '').path
    @back_url = session[:my_previous_url]
  end

  # GET /posts/new
  def new
    if logged_in?
      @post = Post.new
    else
      redirect_to root_path
      flash[:info] = "You're not authorized to make a post"
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    if current_user.admin?
      @post = current_user.posts.build(post_params)
    else
      format.html { redirect_to root, notice: 'You are not authorized to make posts' }
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.friendly.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :picture, :user_id, :topic_id, :caption)
    end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.association :topic, :include_blank => false %>
      <%= f.input :title %>
      <%= f.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
      <br>
      <span class="picture">
        <h3>Try to make pic dimensions close to 2500 x 1600</h3>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %> <%# to validate both internally and on the browser %>
      </span>
      <%= f.input :caption %>
    </div>
    <br>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

<script type="text/javascript">
    $('#micropost_picture').bind('change', function() {
        var size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert('Maximum file size is 5MB. Please choose a smaller file.');
        }
    });
</script>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.name, about_path %></span>
  <span class="content">
    <%= post.content %>
    <%= image_tag post.picture.url if post.picture? %>
  </span>
</li>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Posts Archive</h1>
<div align="center"> <%= form_for posts_path, :method => 'get' do %>
    <p>
      <%= collection_select(:search, :topic_id, Topic.all, :id, :name, {prompt: "All Topics"}, {:class => 'my-custom-class'})%>
      <%= submit_tag "Search", :name => nil, :class => 'my-custom-class'%>
    </p>
<% end %>
  </div>
<hr>
<%= render 'shared/feed' %>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New Post</h1>
<div class="row">
<aside class="col-md-6">
<%= render 'form' %>
</aside>
</div>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title.to_s.html_safe) %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row wrapper">
    <h1>
      <%= raw @post.title %>
    </h1>
    <hr>
    <div class="col-md-7">
      <i>
        By <%= link_to @post.user.name, @post.user %> on <%= @post.created_at.in_time_zone.strftime('%B %d, %Y %I:%M %p') %> <br>
        <% if @post.created_at != @post.updated_at %>
            Updated on <%= @post.updated_at.in_time_zone.strftime('%B %d, %Y %I:%M %p') %>
        <% end %>
      </i>
      <br>
      <br>
      <%= raw @post.content %>
    </div >
    <div class="col-md-5">
      <div>
        <h1>
          <%= image_tag @post.picture.url, :width => "100%" %>
        </h1>
      </div>
      <div class="jumbotron jumbotron-special">
        <h2 id="h2-special">Most Recent Posts</h2>
        <table>
          <thead>
          <td>
            <h5 style="font-weight: bold">Post</h5>
          </td>
          <td>
            <h5 style="font-weight: bold">Date Posted</h5>
          </td>
          </thead>
          <tbody>
          <% @recent_posts.each do |post| %>
              <tr>
                <td style="line-height: normal"><%= link_to post.title.html_safe, post %></td>
                <td><%= post.created_at.in_time_zone.strftime('%m/%d/%y') %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div id="comments" class="col-md-12">
      <hr>
      <div class="row">
        <div class="col-md-7">
          <h2>Comments (<%= @post.comments.count %>)</h2>
          <%= render @post.comments %>
          <h2>Add a comment:</h2>
          <%= render "comments/form" %>
        </div>
      </div>
    </div>
    <% if logged_in? %>
        <h2><%= link_to 'delete', @post, method: :delete, data: {confirm: "You sure?" }%>
          <%= link_to 'edit', edit_post_path(@post) %></h2>
    <% end %>
  </div>
</div>f