config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root                'static_pages#home'
  get    'help'    => 'users#help'
  get    'about'   => 'static_pages#about'
  get    'contact.rb' => 'static_pages#contact.rb'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new' #login page
  post   'login'   => 'sessions#create' #actual log in process
  delete 'logout'  => 'sessions#destroy'
  get    'contacts' => 'contacts#new'

  resources :users do
    member do
      get :following, :followers #member makes sure that the url is users/id/following so the id is included
    end
  end

  resources :posts do
    resources :comments
  end

  resources :topics

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contacts,           only: [:new, :create]


  mount Ckeditor::Engine => '/ckeditor'

end

app/views/layouts/_footer.html.erb
<footer class="footer container">
  <small>
    Coded entirely by hand, and by hand I mean stack overflow and the RoR tutorial
  </small>
  <nav>
    <ul>
      <li><%= link_to "Archives", posts_path %> </li>
      <li><%= link_to "Contact", contacts_path %></li>
      <li><a href="http://www.nyt.com" target="_blank"> News </a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to (image_tag 'favicon.png', height: "35px"), root_path, id: "brand" %>
      <%= link_to "FML Blog", root_path, id: "logo" %>
      <button class="navbar-toggle" data-toggle="collapse" data-target=".myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Film", Topic.find(1), id: "text"%></li>
        <li><%= link_to "Music", Topic.find(2), id: "text"%></li>
        <li><%= link_to "Life", Topic.find(3), id: "text"%></li>
        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li> <%# This uses the final link from the 7.1 listing of the users resource %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
          <%#  <li><%= link_to "Log in", login_path %> </li>
        <% end %>
      </ul>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <%= display_meta_tags  %>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=100%; initial-scale=1.0">
      <%= favicon_link_tag '/favicon.ico' %>
      <title><%= full_title(yield(:title))%></title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato">
      <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Delicious">
      <%= render 'layouts/shim' %>
    </head>
<body>
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%=message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </body>
</html>